### ISSUE TITLE
是否可以在有公网IP的主机上，开启服务端和一个客户端

### ISSUE THREAD

**Issue by thisleo** [optman/rndz#1]
一个客户端和服务端在同一台主机上，并且有公网IP；另一个客户端在内网主机上，这两个客户端是否可以实现连接

**Comment by optman** [comment]
不明白为什么要这么做，既然一个客户端有公网IP直接连就是了（如果有防火墙，打开就是了）。如果一定要做， 公网客户端与服务端时请使用服务端的公网IP（而不能使用localhost或者127.0.0.1），这样服务端观察到的客户端IP就是公网的，另一个内网的客户端就可以连接。
