### ISSUE TITLE
Client connection is dropped.

### ISSUE THREAD

**Issue by uwejan** [optman/rndz#3]
From the examples `tcp` i notice `c1` has the `TcpStream`  but for `c2` it is dropped.
Resuling `broken pipe` if c1 to write anything to c2.
Is this the intended behaviour? How to keep the both c1,c2 connected after disconneting form server?

Thank you,

**Comment by optman** [comment]
both c1 and c2 have `TcpStream`, `c1` write and `c2` read,  i don't see why it cause `broken pipe`, on my linux machine `cargo run --example  demo-tcp` run just fine.

**Comment by uwejan** [comment]
Thank you for taking a look on this. It appears it is a mistake from my end. I am trying to split stream for read/write, while still trying to figure that out, it is causing the issue mentioned.
Since it is not an issue with the lib, am closing. 
Thank you again.
