### ISSUE TITLE
Server using public IP.

### ISSUE THREAD

**Issue by uwejan** [optman/rndz#4]
Using public static IP address for server, then c1, and c2 tryes to connect.
c1 `DEBUG rndz::tcp::client] connect 0.0.0.0:44101 -> PUBLIC_IP:44403`
c2 `DEBUG rndz::tcp::client] Redirect PUBLIC_IP:44101`
Server keeps pinging c1 which indicates it is not successful attempt, as server supposed to drop connectenio on successful attempt.
My question is this library tested on PUBLIC_IP / clients behind multi NAT levels?

Thank you.

**Comment by uwejan** [comment]
![tcp](https://user-images.githubusercontent.com/20250935/224481970-f1333157-3974-42af-85d6-4019231d1a15.png)
Running the server and clients on local network, all works but not when the server is on PUBLIC_IP.
Wirehsark reset flag, screenshot.

**Comment by uwejan** [comment]
Hours of debugging, found out that adding my `internal` ip where my clients are on `vms` to `dmz` zone on the router side will result on successful attempt. Will do more digging as it should not be the case, am i right?

**Comment by optman** [comment]
1. Sever only observe client's outmost ip(no matter how many levels NAT it is behind)
2. You should not run c1 and c2 within the same NAT(you should have two sites to test, or put one of c1/c2 with server), the router may not support NAT hairpin(Maybe that is why you receive RST).
3. IPv4 Holepunch is not guarantee to success.

**Comment by uwejan** [comment]
2. Waht if c1 and c2, are not on the same NAT but using same outbound PUBLIC_IP? I tried that it does not work.
3. I was hoping otherwise, imaginea use case where you do not want to implement local LAN scan to support same LAN devices. Having a single working implementation would actually be a good idea supporting local LAN and WAN devices.
I used STUN before it did solve the issue, I wonder what are your thoughts?

**Comment by uwejan** [comment]
So in order to add more context, I am assuming a scenaryo here;
Say using this network setup 
```
PUBLIC_SERVER_IP = 8.8.8.8 
PUBLIC_ISP_IP = 4.4.4.4
C1_IP = 10.1.1.5
C2_IP = 10.1.1.7
```
The hole-punch will not work, because source and destination are on same NAT router will ignore it. Perhaps resulting RST tcp packet.

Changing `C2_IP = 10.2.1.50` Will actually still not work.
Using `PUBLIC_ISP_IP = 4.4.4.4` for c1, using `PUBLIC_ISP_IP = 4.4.8.8` for c2, will actually works.
It did take sometime to figure this out, as am new to holepunching, but i guise that is how networks and routers operate.

**Comment by optman** [comment]
Yes,  c1 and c2 should not using the same outbound PUBLIC_IP, because it depends on router behaviors([NAT Hairpinning](https://en.wikipedia.org/wiki/Network_address_translation#NAT_hairpinning) may not supported)

A complete solution will have to deal with direct connection(SAME LAN) or through relay(hole punching fail), that should be other projects(There are many already). This crate is simply for hole punching. 

BTW, you can solve the problem by bind to ipv6 address.

**Comment by uwejan** [comment]
Yes for IPV6, among supporting IPv4, perhabs, do some checking for outbound oublic ip used and change bind accordingly.

You have done good work on this crate, Thank you for the implementation :)

I am thinking of a mixed solution.
1. Deal with local LAN.
2. Deal with hole-punching (if fails try relay).
 Are you aware oif a good implementation crates for local LAN discovery, relays?

**Comment by optman** [comment]
`Client::new()` will automatically choose the binding address regard the server address family(ipv4 or v6) if you don't specify the local address.

[libp2p](https://github.com/libp2p/libp2p) is a full solution, everything you need is included.

**Comment by uwejan** [comment]
Brilliant. Going to have a look on it.
Thank you.

**Comment by uwejan** [comment]
Feedback after reading libp2p specs.
https://github.com/libp2p/specs/tree/master/rendezvous#interaction
It seems libp2p has implemented rndz differently. To sum up it is more of a relay, and if you wish to make a directo connection, you will have to implement another protocol https://docs.libp2p.io/concepts/nat/dcutr/.

The way i see it from here is to use your crate for, and deal with local LAN through mDNS.

**Comment by optman** [comment]
libp2p is decentralized system,  every node is  a peer, no server. Any volunteer relay peers can act as rendezvous server.  Before A and B to start hole-punching, they first both connected to R for signal relay. After hole-punching success, the relay connection is upgrade to direct connection, and the relay connection is drop...... It is a long process, and slow.

To accommodate both direct and relay, libp2p need to wrap `TcpStream`, as such it is not easy to be integrated with legacy code. But if you build ground from libp2p, it is advantaged. 

In case you don't care decentralized, use a  dedicated rendezvous server is more efficient. That is why I build `rndz`. And by separate hold-pouching code in a lib, return native `TcpStream`,   incorporated rndz in legacy project is much easy.

**Comment by uwejan** [comment]
Totally make sense. Thanke you for breaking it down for me.
I wonder about the feasiabilty of 2 things with this crate:
1. Have a websocket instead of tcpStream.
2. Rndz server security, perhqbs if could make it websockets i know we could do many things to protect it, but as being tcp server will have to digg more into options available.

**Comment by optman** [comment]
1. Websocket is on top of TCP, and websocket can upgrade from a http connection.
2. As rndz server security, I have thought about it. TLS/DTLS can be used to secure the connection.

**Comment by uwejan** [comment]
1. in terms of websockets, which one of the nodes do you think should be server/client? (c1, c2).
2. I am going to expermit with security, I have an idea in-mind, perhabs isolate security away from rdnz itself.

**Comment by optman** [comment]
Put rndz aside, you need to answer both questions when direct connect
without hole punch.

Saddam UWEJAN ***@***.***> 于 2023年3月16日周四 05:57写道：
